settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: video-playlist
    path: .
    env: 
      SPOTIFY_CLIENT_ID: 
      SPOTIFY_CLIENT_SECRET: 
    args: 
      - -mode=music video
    commands: 
      build: 
        status: true 
        method: 
          go build 
        args: 
          - -o ./bin/video-playlist
          - .
      run: 
        status: true
        method: ./bin/video-playlist
    watcher:
      extensions:
        - go
      paths:
        - /
      ignore:
        paths:
          - .git
          - vendor
